export const FETCH_WEATHERS_START = 'FETCH_WEATHERS_START'
export const FETCH_WEATHERS_SUCCESS = 'FETCH_WEATHERS_SUCCESS'
export const FETCH_WEATHERS_ERROR = 'FETCH_WEATHERS_ERROR'

export const SET_CITY_NAME = 'SET_CITY_NAME'

export const FETCH_WEATHERS_SUCCESS_FIVE_DAYS = 'FETCH_WEATHERS_SUCCESS_FIVE_DAYS'